// <auto-generated />
using System;
using KidsBooks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KidsBooks.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20201112183913_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KidsBooks.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_Added")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Published")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author Name",
                            Date_Added = new DateTime(2020, 11, 12, 13, 39, 11, 849, DateTimeKind.Local).AddTicks(9931),
                            Date_Published = new DateTime(1889, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Book Name",
                            Publisher = "Publisher"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author Name Other",
                            Date_Added = new DateTime(2020, 11, 12, 13, 39, 11, 858, DateTimeKind.Local).AddTicks(3526),
                            Date_Published = new DateTime(1889, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Book Name other",
                            Publisher = "Publisher Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
